public class TWTimeTrack {
/*
	public class Time-entries {
		public String project-id;
		public String isbillable;
		public String todo-list-name;
		public String todo-item-name;
		public String isbilled;
		public String updated-date;
		public String todo-list-id;
		public List<Tags> tags;
		public Boolean canEdit;
		public String taskEstimatedTime;
		public String company-name;
		public String id;
		public String invoiceNo;
		public String person-last-name;
		public String parentTaskName;
		public String dateUserPerspective;
		public String minutes;
		public String person-first-name;
		public String description;
		public String ticket-id;
		public String createdAt;
		public String taskIsPrivate;
		public String parentTaskId;
		public String company-id;
		public String project-status;
		public String person-id;
		public String project-name;
		public List<Tags> task-tags;
		public String taskIsSubTask;
		public String todo-item-id;
		public String date;
		public String has-start-time;
		public String hours;
	}

	public class Tags {
	}

	public class TWTimeTrack {
		public List<Time-entries> time-entries;
		public String STATUS;
	}

	
	public static TWTimeTrack parse(String json) {
		return (TWTimeTrack) System.JSON.deserialize(json, TWTimeTrack.class);
	}*/
}